(()=>{
const slides=[...document.querySelectorAll('.deck-slide')],prev=document.getElementById('prevSlide'),next=document.getElementById('nextSlide'),counter=document.getElementById('slideCount'),progress=document.querySelector('.progress span'),modal=document.getElementById('videoModal'),player=modal?.querySelector('video'),params=new URLSearchParams(location.search);
let idx=Math.min(slides.length-1,Math.max(0,(parseInt(params.get('slide')||'1',10)||1)-1));if(params.get('embedded')==='1')document.body.classList.add('embedded');
function show(n,push=true){idx=Math.min(slides.length-1,Math.max(0,n));slides.forEach((s,i)=>{s.classList.toggle('active',i===idx);s.setAttribute('aria-hidden',i===idx?'false':'true');if(i===idx)s.scrollTop=0;else s.querySelectorAll('video').forEach(v=>v.pause())});prev.disabled=idx===0;next.disabled=idx===slides.length-1;counter.textContent=String(idx+1).padStart(2,'0')+' / '+String(slides.length).padStart(2,'0');progress.style.width=((idx+1)/slides.length*100)+'%';if(push){const u=new URL(location.href);u.searchParams.set('slide',idx+1);history.replaceState(null,'',u)}}
function feedback(v,parent){let box=document.createElement('div');box.className='media-feedback';Object.assign(box.style,{position:'absolute',left:'12px',right:'12px',bottom:'48px',background:'#111e',color:'#fff',padding:'12px',fontSize:'14px',zIndex:8,display:'none'});parent.append(box);function fail(){box.replaceChildren(document.createTextNode('재생이 지연되고 있어요. '));let a=document.createElement('a');a.textContent='영상 직접 열기 ↗';a.href=v.currentSrc||v.src||v.querySelector('source')?.src||'#';a.target='_blank';a.rel='noopener';a.style.color='#fff';box.append(a);box.style.display='block'}v.addEventListener('error',fail);v.addEventListener('playing',()=>box.style.display='none');return {fail,clear:()=>box.style.display='none'}}
for(const v of document.querySelectorAll('.deck-slide video')){const parent=v.parentElement;if(!parent)continue;const button=document.createElement('button');button.type='button';button.className='inline-play';button.setAttribute('aria-label','영상 재생');button.textContent='▶';Object.assign(button.style,{position:'absolute',left:'50%',top:'50%',transform:'translate(-50%,-50%)',width:'72px',height:'72px',border:'2px solid white',borderRadius:'50%',background:'#111b',color:'white',fontSize:'27px',cursor:'pointer',zIndex:5});parent.append(button);let status=feedback(v,parent);button.addEventListener('click',()=>{status.clear();v.play().catch(status.fail)});v.addEventListener('playing',()=>{button.style.display='none';document.querySelectorAll('video').forEach(other=>{if(other!==v)other.pause()})});v.addEventListener('pause',()=>button.style.display='block');v.addEventListener('ended',()=>button.style.display='block')}
const modalStatus=player&&modal?feedback(player,modal):null;function closeModal(){if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');player.pause();player.removeAttribute('src');player.load();modalStatus?.clear()}
prev?.addEventListener('click',()=>show(idx-1));next?.addEventListener('click',()=>show(idx+1));document.addEventListener('keydown',e=>{if(modal?.classList.contains('open')){if(e.key==='Escape')closeModal();return}if(e.target instanceof Element&&e.target.closest('video,a,button,input,textarea,select,[contenteditable]'))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();show(idx+1)}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();show(idx-1)}else if(e.key==='Home'){e.preventDefault();show(0)}else if(e.key==='End'){e.preventDefault();show(slides.length-1)}});
let start=null;document.querySelector('.slides')?.addEventListener('touchstart',e=>{if(e.target.closest('video,button,a'))return;if(e.touches.length===1)start={x:e.touches[0].clientX,y:e.touches[0].clientY}},{passive:true});document.querySelector('.slides')?.addEventListener('touchend',e=>{if(!start||e.changedTouches.length!==1)return;const dx=e.changedTouches[0].clientX-start.x,dy=e.changedTouches[0].clientY-start.y;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.3)show(idx+(dx<0?1:-1));start=null},{passive:true});
document.querySelectorAll('.video-trigger').forEach(b=>b.addEventListener('click',()=>{if(!modal)return;document.querySelectorAll('.deck-slide video').forEach(v=>v.pause());player.poster=b.dataset.poster;player.src=b.dataset.src;player.controls=true;player.playsInline=true;player.preload='metadata';modal.querySelector('.modal-label').textContent=b.dataset.label;modal.classList.add('open');modal.setAttribute('aria-hidden','false');modalStatus.clear();player.play().catch(modalStatus.fail)}));modal?.querySelector('button')?.addEventListener('click',closeModal);modal?.addEventListener('click',e=>{if(e.target===modal)closeModal()});
const printStyle=document.createElement('style');printStyle.textContent='@media print{.inline-play,.media-feedback{display:none!important}}';document.head.append(printStyle);show(idx,false);
})();
